name: Docker Image CI
on:
  push:
    paths-ignore:
      - LICENSE
      - README.md
    branches:
      - master

jobs:
  build:
    name: PHP ${{ matrix.php_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.0", "7.2", "7.3", "7.4", "8.0"]
    steps:
      - uses: actions/checkout@v1
      - name: Change wrapper permissions
        run: chmod +x ./scripts/build.sh
      - name: Run build
        run:  ./scripts/build.sh --push
        env:
          VERSION_LIST: ${{ matrix.php_version }}
          VARIANT_LIST: ${{ matrix.php_variants }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
